services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyChartsDemo\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Wexample\SymfonyChartsDemo\Service\:
        resource: '../../Service/'
